### ISSUE TITLE
Trace satisfiability 

### ISSUE THREAD

**Issue by MFaisalZaki** [Francesco17/LTLf2DFA#74]
It is possible to use LTL2DFA to check a trace satisfiability by passing the trace as an input and see whether the automata will accept it or not?

**Comment by francescofuggitti** [comment]
Hi @MFaisalZaki !

LTLf2DFA is only a library to generate the automata. If you want to check trace satisfiability, you can import the automata into a lib handling automata. My suggestion is [pythomata](https://github.com/whitemech/pythomata). The integration should be easy.
