### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by BobYounger** [Francesco17/LTLf2DFA#75]
When I use this program on Windows, the program would throw an error with "ValueError: preexec_fn is not supported on Windows platforms". I've tried a lot of ways to solve it  but it just won't work.

So I would appreciate it if developers can provide programs which can run on windows

**Comment by francescofuggitti** [comment]
Hi @BobYounger ,

unfortunately, we don't support the Windows platform and we don't have any plan to do it in the future. If you don't have any chance of getting LTLf2DFA to work under a docker or virtual machine, what I can suggest is to use the Windows Subsystem for Linux (WSL).
